codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: '75..95'
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        only_pulls: true
    patch:
      default:
        target: 85%
        threshold: 1%
        informational: true
        only_pulls: true

comment:
  layout: 'condensed_header, diff, flags, files'
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - 'dist/**'
  - 'docs/**'
  - 'scripts/**'
  - 'test/**'
